### ISSUE TITLE
Anchoring on pseudo elements

### ISSUE THREAD

**Issue by jamesnw** [oddbird/css-anchor-positioning#208]
Pseudo elements should be supported as valid anchors. 

From the [spec](https://drafts.csswg.org/css-anchor-position-1/#target), a  `part-like pseudo-element` is a valid anchor.

[Implicit](https://drafts.csswg.org/css-anchor-position-1/#implicit) anchoring of pseudo-elements is specified as well.

**Comment by ayoreis** [comment]
I was working on this (needed it for a project of mine) and got most of the way there but got stuck at getting the position (coordinates) of the pseudo-element. 

I found two ways:

1. Try to calculate it using `element.getBoundingClientRect()` and `getComputedStyle(element, '::pseudo-element-name')`: This is what I started out with but there are too many edge cases to handle.
1. Get the styles of the pseudo-element, hide the pseudo-element, create an new element in place of the pseudo-element with the same styles and get it's position (found here: https://stackoverflow.com/a/27377952): Haven't tested this yet, performance might not be good, this should work for `::before` and `::after` but not sure about other pseudo-elements (also do you know what a "part-like pseudo-element" means?)

Option one works for me because I can handle exactly the cases that matter for me, but I will try option two out tomorrow and if it works open a PR.

**Comment by jamesnw** [comment]
Thanks, @ayoreis! I forgot to give attribution that your work was the reminder that we needed to open this.

> 2\. also do you know what a "part-like pseudo-element" means?

Here's the relevant issue- https://github.com/w3c/csswg-drafts/issues/8615. 

This [commit](https://github.com/w3c/csswg-drafts/commit/6b50e77d1748fb74dd4bcb73616f63158680e400 a) may be helpful as well, as it shows a more verbose description before the `part-like pseudo-element` language is introduced. Essentially, it looks like if you're not able to detect the box, we likely don't need to support it. 

I'm curious to see how the second option turns out!

**Comment by ayoreis** [comment]
Quick update: Got it semi working, don't know about performance yet, tomorrow I will try to have it fully working and test performance.

**Comment by jamesnw** [comment]
@ayoreis I tracked down a better definition of `part-like pseudo-elements` here- https://drafts.csswg.org/css-pseudo-4/#part-like-pseudo-elements

Essentially, we should also be able to support-

- `::file-selector-button` (anchoring is currently supported in Chromium)
- `::details-content` (this is only a proposed pseudo element at this point, there is no browser support yet.)

Will the fake element strategy work for these? 

Outside of standard pseudo elements, it would be _nice_ if we could support `::-webkit-slider-thumb`, but that's tricky as it isn't cross-browser.

**Comment by ayoreis** [comment]
Not really, since the fake element technique needs to replace the pseudo-element with a real element for a moment, and input element can't have children.

For the `::details-content` pseudo-element, when browsers support it they will probably also support anchor positioning.

I just had another idea which might work tough, if I set the pseudo-element to `position: absolute;` and `inset: auto;`, then `getComputedStyle(element, '::pseudo-element-name')` should give enough info on the element position. This would not have the same limitation, testing it right now.
